### ISSUE TITLE
请问如何用自己的数据进行test呢？谢谢！

### ISSUE THREAD

**Issue by songsong695** [QT-Zhu/SatelliteExtract#1]
使用train.py  --mode='test'时需要对应的mask

**Comment by QT-Zhu** [comment]
这是因为test实际上指的是在数据集的测试集上测出性能指标，如果希望测试自己的数据（无GT的情况）的话，可以修改数据集的定义（在`utils/AerialDataset.py`中），把GT的载入注释掉，再在`Trainer.py`中把性能计算的步骤注释掉就行了。

**Comment by songsong695** [comment]
好的，十分感谢您！
